export const SUBMIT_LOGIN_DATA_REQUEST = 'SUBMIT_LOGIN_DATA_REQUEST'
export const SUBMIT_LOGIN_DATA_SUCCESS = 'SUBMIT_LOGIN_DATA_SUCCESS'
export const SUBMIT_LOGIN_DATA_ERR = 'SUBMIT_LOGIN_DATA_ERR'


export const OTP_VERIFIED_REQUEST = 'OTP_VERIFIED_REQUEST'
export const OTP_VERIFIED_SUCCESS = 'OTP_VERIFIED_SUCCESS'
export const OTP_VERIFIED_ERR = 'OTP_VERIFIED_ERR'

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_ERR = 'USER_LOGOUT_ERR'