import type { Metadata } from "next";
import { Toaster } from "react-hot-toast"; // ✅ Import this at the top
import { Geist, Geist_Mono, Inria_Serif } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { Irish_Grover } from "next/font/google";
import Footer from "@/components/layout/footer";
import MobileNav from "@/components/layout/mobileNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const irishGrover = Irish_Grover({
  subsets: ["latin"],
  weight: "400", // Irish Grover only has 400 weight
  variable: "--font-irish-grover", // Custom CSS variable
});

const inriaSerif = Inria_Serif({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inria-serif",
})

export const metadata: Metadata = {
  title: "Baleryon",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${irishGrover.variable} ${inriaSerif.variable} antialiased`}
      >
        <ReduxProvider>
        <Toaster position="top-right" reverseOrder={false} />
          <Header />
          {children}
          <Footer/>
          <MobileNav />
        </ReduxProvider>
      </body>
    </html>
  );
}
